// <auto-generated />
namespace ConsoleApplication7.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class WithAbstract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WithAbstract));
        
        string IMigrationMetadata.Id
        {
            get { return "201307260108011_WithAbstract"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
